# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f06f034bc45ff5f6b901bd9097f6685a279cde8f482458eba993d504563608fad20dac90814f6487f66a5dfb51fa1d4548a0b786e618c4ac14917bb368a610bc

test:
  secret_key_base: 0167f0e1f23b1fd3632bece63644900c6398abfd0827cb1174ddbcd7283ace02dc1c39ac68f3071af3e463826a0e6647462109bec46d2575e9006df949ad136c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
